/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface LuckyNumberLotteryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ENTRY_FEE"
      | "endLottery"
      | "getContractBalance"
      | "getLotteryStatus"
      | "getParticipant"
      | "getWinningNumber"
      | "hasUserParticipated"
      | "protocolId"
      | "revealedWinningNumber"
      | "submitNumber"
      | "winner"
      | "withdrawFunds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "LotteryEnded" | "ParticipantJoined"
  ): EventFragment;

  encodeFunctionData(functionFragment: "ENTRY_FEE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "endLottery",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContractBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLotteryStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getParticipant",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWinningNumber",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasUserParticipated",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revealedWinningNumber",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitNumber",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "winner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawFunds",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "ENTRY_FEE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "endLottery", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getContractBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLotteryStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParticipant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWinningNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasUserParticipated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revealedWinningNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "winner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFunds",
    data: BytesLike
  ): Result;
}

export namespace LotteryEndedEvent {
  export type InputTuple = [
    winner: AddressLike,
    winningNumber: BigNumberish,
    totalParticipants: BigNumberish
  ];
  export type OutputTuple = [
    winner: string,
    winningNumber: bigint,
    totalParticipants: bigint
  ];
  export interface OutputObject {
    winner: string;
    winningNumber: bigint;
    totalParticipants: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ParticipantJoinedEvent {
  export type InputTuple = [user: AddressLike, participantCount: BigNumberish];
  export type OutputTuple = [user: string, participantCount: bigint];
  export interface OutputObject {
    user: string;
    participantCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LuckyNumberLottery extends BaseContract {
  connect(runner?: ContractRunner | null): LuckyNumberLottery;
  waitForDeployment(): Promise<this>;

  interface: LuckyNumberLotteryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ENTRY_FEE: TypedContractMethod<[], [bigint], "view">;

  endLottery: TypedContractMethod<[], [void], "nonpayable">;

  getContractBalance: TypedContractMethod<[], [bigint], "view">;

  getLotteryStatus: TypedContractMethod<
    [],
    [
      [boolean, string, bigint, bigint] & {
        _lotteryEnded: boolean;
        _winner: string;
        _winningNumber: bigint;
        _participantCount: bigint;
      }
    ],
    "view"
  >;

  getParticipant: TypedContractMethod<
    [user: AddressLike],
    [
      [boolean, string, string] & {
        userHasParticipated: boolean;
        encryptedNumber: string;
        isWinner: string;
      }
    ],
    "view"
  >;

  getWinningNumber: TypedContractMethod<[], [string], "view">;

  hasUserParticipated: TypedContractMethod<
    [user: AddressLike],
    [boolean],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  revealedWinningNumber: TypedContractMethod<[], [bigint], "view">;

  submitNumber: TypedContractMethod<
    [encryptedNumber: BytesLike, inputProof: BytesLike],
    [void],
    "payable"
  >;

  winner: TypedContractMethod<[], [string], "view">;

  withdrawFunds: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ENTRY_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "endLottery"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getContractBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLotteryStatus"
  ): TypedContractMethod<
    [],
    [
      [boolean, string, bigint, bigint] & {
        _lotteryEnded: boolean;
        _winner: string;
        _winningNumber: bigint;
        _participantCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getParticipant"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [boolean, string, string] & {
        userHasParticipated: boolean;
        encryptedNumber: string;
        isWinner: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWinningNumber"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "hasUserParticipated"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "revealedWinningNumber"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitNumber"
  ): TypedContractMethod<
    [encryptedNumber: BytesLike, inputProof: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "winner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawFunds"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "LotteryEnded"
  ): TypedContractEvent<
    LotteryEndedEvent.InputTuple,
    LotteryEndedEvent.OutputTuple,
    LotteryEndedEvent.OutputObject
  >;
  getEvent(
    key: "ParticipantJoined"
  ): TypedContractEvent<
    ParticipantJoinedEvent.InputTuple,
    ParticipantJoinedEvent.OutputTuple,
    ParticipantJoinedEvent.OutputObject
  >;

  filters: {
    "LotteryEnded(address,uint8,uint256)": TypedContractEvent<
      LotteryEndedEvent.InputTuple,
      LotteryEndedEvent.OutputTuple,
      LotteryEndedEvent.OutputObject
    >;
    LotteryEnded: TypedContractEvent<
      LotteryEndedEvent.InputTuple,
      LotteryEndedEvent.OutputTuple,
      LotteryEndedEvent.OutputObject
    >;

    "ParticipantJoined(address,uint256)": TypedContractEvent<
      ParticipantJoinedEvent.InputTuple,
      ParticipantJoinedEvent.OutputTuple,
      ParticipantJoinedEvent.OutputObject
    >;
    ParticipantJoined: TypedContractEvent<
      ParticipantJoinedEvent.InputTuple,
      ParticipantJoinedEvent.OutputTuple,
      ParticipantJoinedEvent.OutputObject
    >;
  };
}
