/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SimpleLotteryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ENTRY_FEE"
      | "endLottery"
      | "getContractBalance"
      | "getLotteryStatus"
      | "getParticipant"
      | "hasParticipated"
      | "lotteryEnded"
      | "participants"
      | "submitNumber"
      | "winner"
      | "winningNumber"
      | "withdrawFunds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "LotteryEnded" | "ParticipantJoined"
  ): EventFragment;

  encodeFunctionData(functionFragment: "ENTRY_FEE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "endLottery",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContractBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLotteryStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getParticipant",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasParticipated",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lotteryEnded",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "participants",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitNumber",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "winner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "winningNumber",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFunds",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "ENTRY_FEE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "endLottery", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getContractBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLotteryStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParticipant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasParticipated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lotteryEnded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "participants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "winner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "winningNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFunds",
    data: BytesLike
  ): Result;
}

export namespace LotteryEndedEvent {
  export type InputTuple = [
    winner: AddressLike,
    winningNumber: BigNumberish,
    totalParticipants: BigNumberish
  ];
  export type OutputTuple = [
    winner: string,
    winningNumber: bigint,
    totalParticipants: bigint
  ];
  export interface OutputObject {
    winner: string;
    winningNumber: bigint;
    totalParticipants: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ParticipantJoinedEvent {
  export type InputTuple = [user: AddressLike, number: BigNumberish];
  export type OutputTuple = [user: string, number: bigint];
  export interface OutputObject {
    user: string;
    number: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SimpleLottery extends BaseContract {
  connect(runner?: ContractRunner | null): SimpleLottery;
  waitForDeployment(): Promise<this>;

  interface: SimpleLotteryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ENTRY_FEE: TypedContractMethod<[], [bigint], "view">;

  endLottery: TypedContractMethod<[], [void], "nonpayable">;

  getContractBalance: TypedContractMethod<[], [bigint], "view">;

  getLotteryStatus: TypedContractMethod<
    [],
    [
      [boolean, string, bigint, bigint] & {
        _lotteryEnded: boolean;
        _winner: string;
        _winningNumber: bigint;
        _participantCount: bigint;
      }
    ],
    "view"
  >;

  getParticipant: TypedContractMethod<
    [index: BigNumberish],
    [
      [string, bigint, boolean] & {
        user: string;
        number: bigint;
        participated: boolean;
      }
    ],
    "view"
  >;

  hasParticipated: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  lotteryEnded: TypedContractMethod<[], [boolean], "view">;

  participants: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, boolean] & {
        user: string;
        number: bigint;
        hasParticipated: boolean;
      }
    ],
    "view"
  >;

  submitNumber: TypedContractMethod<[number: BigNumberish], [void], "payable">;

  winner: TypedContractMethod<[], [string], "view">;

  winningNumber: TypedContractMethod<[], [bigint], "view">;

  withdrawFunds: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ENTRY_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "endLottery"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getContractBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLotteryStatus"
  ): TypedContractMethod<
    [],
    [
      [boolean, string, bigint, bigint] & {
        _lotteryEnded: boolean;
        _winner: string;
        _winningNumber: bigint;
        _participantCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getParticipant"
  ): TypedContractMethod<
    [index: BigNumberish],
    [
      [string, bigint, boolean] & {
        user: string;
        number: bigint;
        participated: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasParticipated"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lotteryEnded"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "participants"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, boolean] & {
        user: string;
        number: bigint;
        hasParticipated: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitNumber"
  ): TypedContractMethod<[number: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "winner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "winningNumber"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawFunds"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "LotteryEnded"
  ): TypedContractEvent<
    LotteryEndedEvent.InputTuple,
    LotteryEndedEvent.OutputTuple,
    LotteryEndedEvent.OutputObject
  >;
  getEvent(
    key: "ParticipantJoined"
  ): TypedContractEvent<
    ParticipantJoinedEvent.InputTuple,
    ParticipantJoinedEvent.OutputTuple,
    ParticipantJoinedEvent.OutputObject
  >;

  filters: {
    "LotteryEnded(address,uint8,uint256)": TypedContractEvent<
      LotteryEndedEvent.InputTuple,
      LotteryEndedEvent.OutputTuple,
      LotteryEndedEvent.OutputObject
    >;
    LotteryEnded: TypedContractEvent<
      LotteryEndedEvent.InputTuple,
      LotteryEndedEvent.OutputTuple,
      LotteryEndedEvent.OutputObject
    >;

    "ParticipantJoined(address,uint8)": TypedContractEvent<
      ParticipantJoinedEvent.InputTuple,
      ParticipantJoinedEvent.OutputTuple,
      ParticipantJoinedEvent.OutputObject
    >;
    ParticipantJoined: TypedContractEvent<
      ParticipantJoinedEvent.InputTuple,
      ParticipantJoinedEvent.OutputTuple,
      ParticipantJoinedEvent.OutputObject
    >;
  };
}
